from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AcquisitionRegionsDialog(object):
    def setupUi(self, AcquisitionRegionsDialog):
        AcquisitionRegionsDialog.setObjectName("AcquisitionRegionsDialog")
        AcquisitionRegionsDialog.resize(809, 885)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        AcquisitionRegionsDialog.setFont(font)
        self.ls_region_label = QtWidgets.QLabel(AcquisitionRegionsDialog)
        self.ls_region_label.setGeometry(QtCore.QRect(150, 10, 301, 61))
        self.ls_region_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ls_region_label.setObjectName("ls_region_label")
        self.region_label = QtWidgets.QLabel(AcquisitionRegionsDialog)
        self.region_label.setGeometry(QtCore.QRect(270, 90, 61, 16))
        self.region_label.setAlignment(QtCore.Qt.AlignCenter)
        self.region_label.setObjectName("region_label")
        self.fish_label = QtWidgets.QLabel(AcquisitionRegionsDialog)
        self.fish_label.setGeometry(QtCore.QRect(260, 70, 71, 16))
        self.fish_label.setAlignment(QtCore.Qt.AlignCenter)
        self.fish_label.setObjectName("fish_label")
        self.x_label = QtWidgets.QLabel(AcquisitionRegionsDialog)
        self.x_label.setGeometry(QtCore.QRect(200, 170, 47, 16))
        self.x_label.setAlignment(QtCore.Qt.AlignCenter)
        self.x_label.setObjectName("x_label")
        self.y_label = QtWidgets.QLabel(AcquisitionRegionsDialog)
        self.y_label.setGeometry(QtCore.QRect(200, 200, 47, 16))
        self.y_label.setAlignment(QtCore.Qt.AlignCenter)
        self.y_label.setObjectName("y_label")
        self.z_label = QtWidgets.QLabel(AcquisitionRegionsDialog)
        self.z_label.setGeometry(QtCore.QRect(200, 230, 47, 21))
        self.z_label.setAlignment(QtCore.Qt.AlignCenter)
        self.z_label.setObjectName("z_label")
        self.x_line_edit = QtWidgets.QLineEdit(AcquisitionRegionsDialog)
        self.x_line_edit.setGeometry(QtCore.QRect(240, 170, 113, 20))
        self.x_line_edit.setObjectName("x_line_edit")
        self.y_line_edit = QtWidgets.QLineEdit(AcquisitionRegionsDialog)
        self.y_line_edit.setGeometry(QtCore.QRect(240, 200, 113, 20))
        self.y_line_edit.setObjectName("y_line_edit")
        self.z_line_edit = QtWidgets.QLineEdit(AcquisitionRegionsDialog)
        self.z_line_edit.setGeometry(QtCore.QRect(240, 230, 113, 20))
        self.z_line_edit.setObjectName("z_line_edit")
        self.set_region_button = QtWidgets.QPushButton(AcquisitionRegionsDialog)
        self.set_region_button.setGeometry(QtCore.QRect(260, 140, 75, 23))
        self.set_region_button.setObjectName("set_region_button")
        self.previous_fish_button = QtWidgets.QPushButton(AcquisitionRegionsDialog)
        self.previous_fish_button.setGeometry(QtCore.QRect(24, 270, 101, 23))
        self.previous_fish_button.setObjectName("previous_fish_button")
        self.previous_region_button = QtWidgets.QPushButton(AcquisitionRegionsDialog)
        self.previous_region_button.setGeometry(QtCore.QRect(130, 270, 101, 23))
        self.previous_region_button.setObjectName("previous_region_button")
        self.next_region_button = QtWidgets.QPushButton(AcquisitionRegionsDialog)
        self.next_region_button.setGeometry(QtCore.QRect(370, 270, 81, 23))
        self.next_region_button.setObjectName("next_region_button")
        self.next_fish_button = QtWidgets.QPushButton(AcquisitionRegionsDialog)
        self.next_fish_button.setGeometry(QtCore.QRect(460, 270, 91, 23))
        self.next_fish_button.setObjectName("next_fish_button")
        self.remove_region_button = QtWidgets.QPushButton(AcquisitionRegionsDialog)
        self.remove_region_button.setGeometry(QtCore.QRect(244, 270, 111, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.remove_region_button.setFont(font)
        self.remove_region_button.setObjectName("remove_region_button")
        self.snap_exposure_line_edit = QtWidgets.QLineEdit(AcquisitionRegionsDialog)
        self.snap_exposure_line_edit.setGeometry(QtCore.QRect(382, 360, 61, 20))
        self.snap_exposure_line_edit.setObjectName("snap_exposure_line_edit")
        self.snap_exposure_time_label = QtWidgets.QLabel(AcquisitionRegionsDialog)
        self.snap_exposure_time_label.setGeometry(QtCore.QRect(290, 360, 91, 16))
        self.snap_exposure_time_label.setAlignment(QtCore.Qt.AlignCenter)
        self.snap_exposure_time_label.setObjectName("snap_exposure_time_label")
        self.snap_exposure_unit_label = QtWidgets.QLabel(AcquisitionRegionsDialog)
        self.snap_exposure_unit_label.setGeometry(QtCore.QRect(450, 360, 21, 20))
        self.snap_exposure_unit_label.setAlignment(QtCore.Qt.AlignCenter)
        self.snap_exposure_unit_label.setObjectName("snap_exposure_unit_label")
        self.start_z_label = QtWidgets.QLabel(AcquisitionRegionsDialog)
        self.start_z_label.setGeometry(QtCore.QRect(50, 360, 47, 21))
        self.start_z_label.setAlignment(QtCore.Qt.AlignCenter)
        self.start_z_label.setObjectName("start_z_label")
        self.start_z_line_edit = QtWidgets.QLineEdit(AcquisitionRegionsDialog)
        self.start_z_line_edit.setGeometry(QtCore.QRect(100, 360, 113, 20))
        self.start_z_line_edit.setObjectName("start_z_line_edit")
        self.end_z_label = QtWidgets.QLabel(AcquisitionRegionsDialog)
        self.end_z_label.setGeometry(QtCore.QRect(50, 390, 47, 21))
        self.end_z_label.setAlignment(QtCore.Qt.AlignCenter)
        self.end_z_label.setObjectName("end_z_label")
        self.end_z_line_edit = QtWidgets.QLineEdit(AcquisitionRegionsDialog)
        self.end_z_line_edit.setGeometry(QtCore.QRect(100, 390, 113, 20))
        self.end_z_line_edit.setObjectName("end_z_line_edit")
        self.step_size_label = QtWidgets.QLabel(AcquisitionRegionsDialog)
        self.step_size_label.setGeometry(QtCore.QRect(50, 420, 47, 21))
        self.step_size_label.setAlignment(QtCore.Qt.AlignCenter)
        self.step_size_label.setObjectName("step_size_label")
        self.step_size_line_edit = QtWidgets.QLineEdit(AcquisitionRegionsDialog)
        self.step_size_line_edit.setGeometry(QtCore.QRect(100, 420, 111, 20))
        self.step_size_line_edit.setObjectName("step_size_line_edit")
        self.start_z_unit_label = QtWidgets.QLabel(AcquisitionRegionsDialog)
        self.start_z_unit_label.setGeometry(QtCore.QRect(220, 360, 21, 20))
        self.start_z_unit_label.setAlignment(QtCore.Qt.AlignCenter)
        self.start_z_unit_label.setObjectName("start_z_unit_label")
        self.end_z_unit_label = QtWidgets.QLabel(AcquisitionRegionsDialog)
        self.end_z_unit_label.setGeometry(QtCore.QRect(220, 390, 21, 20))
        self.end_z_unit_label.setAlignment(QtCore.Qt.AlignCenter)
        self.end_z_unit_label.setObjectName("end_z_unit_label")
        self.step_size_unit_label = QtWidgets.QLabel(AcquisitionRegionsDialog)
        self.step_size_unit_label.setGeometry(QtCore.QRect(220, 420, 21, 20))
        self.step_size_unit_label.setAlignment(QtCore.Qt.AlignCenter)
        self.step_size_unit_label.setObjectName("step_size_unit_label")
        self.x_unit_label = QtWidgets.QLabel(AcquisitionRegionsDialog)
        self.x_unit_label.setGeometry(QtCore.QRect(320, 170, 91, 16))
        self.x_unit_label.setWhatsThis("")
        self.x_unit_label.setAlignment(QtCore.Qt.AlignCenter)
        self.x_unit_label.setObjectName("x_unit_label")
        self.y_unit_label = QtWidgets.QLabel(AcquisitionRegionsDialog)
        self.y_unit_label.setGeometry(QtCore.QRect(320, 200, 91, 16))
        self.y_unit_label.setAlignment(QtCore.Qt.AlignCenter)
        self.y_unit_label.setObjectName("y_unit_label")
        self.z_unit_label = QtWidgets.QLabel(AcquisitionRegionsDialog)
        self.z_unit_label.setGeometry(QtCore.QRect(320, 230, 91, 16))
        self.z_unit_label.setAlignment(QtCore.Qt.AlignCenter)
        self.z_unit_label.setObjectName("z_unit_label")
        self.video_exposure_line_edit = QtWidgets.QLineEdit(AcquisitionRegionsDialog)
        self.video_exposure_line_edit.setGeometry(QtCore.QRect(652, 390, 61, 20))
        self.video_exposure_line_edit.setObjectName("video_exposure_line_edit")
        self.video_exposure_unit_label = QtWidgets.QLabel(AcquisitionRegionsDialog)
        self.video_exposure_unit_label.setGeometry(QtCore.QRect(680, 390, 91, 16))
        self.video_exposure_unit_label.setAlignment(QtCore.Qt.AlignCenter)
        self.video_exposure_unit_label.setObjectName("video_exposure_unit_label")
        self.video_exposure_time_label = QtWidgets.QLabel(AcquisitionRegionsDialog)
        self.video_exposure_time_label.setGeometry(QtCore.QRect(560, 390, 91, 16))
        self.video_exposure_time_label.setAlignment(QtCore.Qt.AlignCenter)
        self.video_exposure_time_label.setObjectName("video_exposure_time_label")
        self.video_num_frames_line_edit = QtWidgets.QLineEdit(AcquisitionRegionsDialog)
        self.video_num_frames_line_edit.setGeometry(QtCore.QRect(650, 360, 61, 20))
        self.video_num_frames_line_edit.setText("")
        self.video_num_frames_line_edit.setObjectName("video_num_frames_line_edit")
        self.video_num_frames_label = QtWidgets.QLabel(AcquisitionRegionsDialog)
        self.video_num_frames_label.setGeometry(QtCore.QRect(550, 360, 101, 20))
        self.video_num_frames_label.setAlignment(QtCore.Qt.AlignCenter)
        self.video_num_frames_label.setObjectName("video_num_frames_label")
        self.region_table_view = QtWidgets.QTableView(AcquisitionRegionsDialog)
        self.region_table_view.setGeometry(QtCore.QRect(30, 690, 801, 161))
        self.region_table_view.setObjectName("region_table_view")
        self.line = QtWidgets.QFrame(AcquisitionRegionsDialog)
        self.line.setGeometry(QtCore.QRect(0, 300, 911, 16))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(8)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(AcquisitionRegionsDialog)
        self.line_2.setGeometry(QtCore.QRect(260, 310, 20, 371))
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(8)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(AcquisitionRegionsDialog)
        self.line_3.setGeometry(QtCore.QRect(530, 310, 20, 371))
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setLineWidth(8)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(AcquisitionRegionsDialog)
        self.line_4.setGeometry(QtCore.QRect(0, 670, 911, 16))
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setLineWidth(8)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        self.acquisition_setup_button = QtWidgets.QPushButton(AcquisitionRegionsDialog)
        self.acquisition_setup_button.setGeometry(QtCore.QRect(380, 860, 111, 23))
        self.acquisition_setup_button.setObjectName("acquisition_setup_button")
        self.z_stack_available_list_view = QtWidgets.QListView(AcquisitionRegionsDialog)
        self.z_stack_available_list_view.setGeometry(QtCore.QRect(60, 490, 71, 121))
        self.z_stack_available_list_view.setObjectName("z_stack_available_list_view")
        self.video_used_label = QtWidgets.QLabel(AcquisitionRegionsDialog)
        self.video_used_label.setGeometry(QtCore.QRect(700, 470, 47, 21))
        self.video_used_label.setAlignment(QtCore.Qt.AlignCenter)
        self.video_used_label.setObjectName("video_used_label")
        self.used_z_stack_label = QtWidgets.QLabel(AcquisitionRegionsDialog)
        self.used_z_stack_label.setGeometry(QtCore.QRect(160, 470, 47, 21))
        self.used_z_stack_label.setAlignment(QtCore.Qt.AlignCenter)
        self.used_z_stack_label.setObjectName("used_z_stack_label")
        self.snap_available_label = QtWidgets.QLabel(AcquisitionRegionsDialog)
        self.snap_available_label.setGeometry(QtCore.QRect(320, 469, 71, 21))
        self.snap_available_label.setAlignment(QtCore.Qt.AlignCenter)
        self.snap_available_label.setObjectName("snap_available_label")
        self.snap_channel_label = QtWidgets.QLabel(AcquisitionRegionsDialog)
        self.snap_channel_label.setGeometry(QtCore.QRect(370, 450, 61, 20))
        self.snap_channel_label.setAlignment(QtCore.Qt.AlignCenter)
        self.snap_channel_label.setObjectName("snap_channel_label")
        self.video_channel_label = QtWidgets.QLabel(AcquisitionRegionsDialog)
        self.video_channel_label.setGeometry(QtCore.QRect(650, 450, 61, 20))
        self.video_channel_label.setAlignment(QtCore.Qt.AlignCenter)
        self.video_channel_label.setObjectName("video_channel_label")
        self.z_stack_used_list_view = QtWidgets.QListView(AcquisitionRegionsDialog)
        self.z_stack_used_list_view.setGeometry(QtCore.QRect(150, 490, 71, 121))
        self.z_stack_used_list_view.setObjectName("z_stack_used_list_view")
        self.snap_used_label = QtWidgets.QLabel(AcquisitionRegionsDialog)
        self.snap_used_label.setGeometry(QtCore.QRect(420, 470, 47, 21))
        self.snap_used_label.setAlignment(QtCore.Qt.AlignCenter)
        self.snap_used_label.setObjectName("snap_used_label")
        self.video_used_list_view = QtWidgets.QListView(AcquisitionRegionsDialog)
        self.video_used_list_view.setGeometry(QtCore.QRect(690, 490, 71, 121))
        self.video_used_list_view.setObjectName("video_used_list_view")
        self.available_z_stack_label = QtWidgets.QLabel(AcquisitionRegionsDialog)
        self.available_z_stack_label.setGeometry(QtCore.QRect(66, 470, 51, 20))
        self.available_z_stack_label.setAlignment(QtCore.Qt.AlignCenter)
        self.available_z_stack_label.setObjectName("available_z_stack_label")
        self.snap_used_list_view = QtWidgets.QListView(AcquisitionRegionsDialog)
        self.snap_used_list_view.setGeometry(QtCore.QRect(410, 490, 71, 121))
        self.snap_used_list_view.setObjectName("snap_used_list_view")
        self.z_stack_channel_label = QtWidgets.QLabel(AcquisitionRegionsDialog)
        self.z_stack_channel_label.setGeometry(QtCore.QRect(116, 450, 51, 20))
        self.z_stack_channel_label.setAlignment(QtCore.Qt.AlignCenter)
        self.z_stack_channel_label.setObjectName("z_stack_channel_label")
        self.snap_available_list_view = QtWidgets.QListView(AcquisitionRegionsDialog)
        self.snap_available_list_view.setGeometry(QtCore.QRect(320, 490, 71, 121))
        self.snap_available_list_view.setObjectName("snap_available_list_view")
        self.video_available_label = QtWidgets.QLabel(AcquisitionRegionsDialog)
        self.video_available_label.setGeometry(QtCore.QRect(600, 470, 71, 20))
        self.video_available_label.setAlignment(QtCore.Qt.AlignCenter)
        self.video_available_label.setObjectName("video_available_label")
        self.video_available_list_view = QtWidgets.QListView(AcquisitionRegionsDialog)
        self.video_available_list_view.setGeometry(QtCore.QRect(600, 490, 71, 121))
        self.video_available_list_view.setObjectName("video_available_list_view")
        self.copy_region_button = QtWidgets.QPushButton(AcquisitionRegionsDialog)
        self.copy_region_button.setGeometry(QtCore.QRect(34, 170, 91, 23))
        self.copy_region_button.setObjectName("copy_region_button")
        self.paste_region_button = QtWidgets.QPushButton(AcquisitionRegionsDialog)
        self.paste_region_button.setGeometry(QtCore.QRect(34, 200, 91, 23))
        self.paste_region_button.setObjectName("paste_region_button")
        self.set_z_start_button = QtWidgets.QPushButton(AcquisitionRegionsDialog)
        self.set_z_start_button.setGeometry(QtCore.QRect(10, 360, 41, 23))
        self.set_z_start_button.setObjectName("set_z_start_button")
        self.set_z_end_button = QtWidgets.QPushButton(AcquisitionRegionsDialog)
        self.set_z_end_button.setGeometry(QtCore.QRect(10, 390, 41, 23))
        self.set_z_end_button.setObjectName("set_z_end_button")
        self.go_to_button = QtWidgets.QPushButton(AcquisitionRegionsDialog)
        self.go_to_button.setGeometry(QtCore.QRect(260, 110, 75, 23))
        self.go_to_button.setObjectName("go_to_button")
        self.z_stack_check_box = QtWidgets.QCheckBox(AcquisitionRegionsDialog)
        self.z_stack_check_box.setGeometry(QtCore.QRect(100, 320, 70, 17))
        self.z_stack_check_box.setObjectName("z_stack_check_box")
        self.snap_check_box = QtWidgets.QCheckBox(AcquisitionRegionsDialog)
        self.snap_check_box.setGeometry(QtCore.QRect(380, 320, 70, 17))
        self.snap_check_box.setObjectName("snap_check_box")
        self.video_check_box = QtWidgets.QCheckBox(AcquisitionRegionsDialog)
        self.video_check_box.setGeometry(QtCore.QRect(650, 320, 70, 17))
        self.video_check_box.setObjectName("video_check_box")
        self.reset_joystick_button = QtWidgets.QPushButton(AcquisitionRegionsDialog)
        self.reset_joystick_button.setGeometry(QtCore.QRect(640, 860, 111, 23))
        self.reset_joystick_button.setObjectName("reset_joystick_button")
        self.add_notes_text_edit = QtWidgets.QPlainTextEdit(AcquisitionRegionsDialog)
        self.add_notes_text_edit.setGeometry(QtCore.QRect(570, 180, 161, 71))
        self.add_notes_text_edit.setObjectName("add_notes_text_edit")
        self.age_label = QtWidgets.QLabel(AcquisitionRegionsDialog)
        self.age_label.setGeometry(QtCore.QRect(540, 110, 21, 16))
        self.age_label.setObjectName("age_label")
        self.inoculum_line_edit = QtWidgets.QLineEdit(AcquisitionRegionsDialog)
        self.inoculum_line_edit.setGeometry(QtCore.QRect(570, 140, 161, 20))
        self.inoculum_line_edit.setText("")
        self.inoculum_line_edit.setObjectName("inoculum_line_edit")
        self.additional_notes_label = QtWidgets.QLabel(AcquisitionRegionsDialog)
        self.additional_notes_label.setGeometry(QtCore.QRect(480, 180, 81, 20))
        self.additional_notes_label.setObjectName("additional_notes_label")
        self.fish_type_line_edit = QtWidgets.QLineEdit(AcquisitionRegionsDialog)
        self.fish_type_line_edit.setGeometry(QtCore.QRect(570, 80, 161, 20))
        self.fish_type_line_edit.setObjectName("fish_type_line_edit")
        self.inoculum_label = QtWidgets.QLabel(AcquisitionRegionsDialog)
        self.inoculum_label.setGeometry(QtCore.QRect(520, 140, 51, 20))
        self.inoculum_label.setObjectName("inoculum_label")
        self.fish_type_label = QtWidgets.QLabel(AcquisitionRegionsDialog)
        self.fish_type_label.setGeometry(QtCore.QRect(510, 80, 61, 20))
        self.fish_type_label.setObjectName("fish_type_label")
        self.age_line_edit = QtWidgets.QLineEdit(AcquisitionRegionsDialog)
        self.age_line_edit.setGeometry(QtCore.QRect(570, 110, 161, 20))
        self.age_line_edit.setObjectName("age_line_edit")
        self.fish_notes_label = QtWidgets.QLabel(AcquisitionRegionsDialog)
        self.fish_notes_label.setGeometry(QtCore.QRect(530, 20, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.fish_notes_label.setFont(font)
        self.fish_notes_label.setAlignment(QtCore.Qt.AlignCenter)
        self.fish_notes_label.setObjectName("fish_notes_label")

        self.retranslateUi(AcquisitionRegionsDialog)
        QtCore.QMetaObject.connectSlotsByName(AcquisitionRegionsDialog)

    def retranslateUi(self, AcquisitionRegionsDialog):
        _translate = QtCore.QCoreApplication.translate
        AcquisitionRegionsDialog.setWindowTitle(_translate("AcquisitionRegionsDialog", "Regions"))
        self.ls_region_label.setText(_translate("AcquisitionRegionsDialog", "<html><head/><body><p><span style=\" font-size:20pt;\">Acquistion Region Setup</span></p></body></html>"))
        self.region_label.setText(_translate("AcquisitionRegionsDialog", "Region 1"))
        self.fish_label.setText(_translate("AcquisitionRegionsDialog", "Sample 1"))
        self.x_label.setText(_translate("AcquisitionRegionsDialog", "X:"))
        self.y_label.setText(_translate("AcquisitionRegionsDialog", "Y:"))
        self.z_label.setText(_translate("AcquisitionRegionsDialog", "Z:"))
        self.x_line_edit.setWhatsThis(_translate("AcquisitionRegionsDialog", "<html><head/><body><p>X position of current region</p></body></html>"))
        self.y_line_edit.setWhatsThis(_translate("AcquisitionRegionsDialog", "<html><head/><body><p>Y position of current region</p></body></html>"))
        self.z_line_edit.setWhatsThis(_translate("AcquisitionRegionsDialog", "<html><head/><body><p>Z position of current region</p></body></html>"))
        self.set_region_button.setWhatsThis(_translate("AcquisitionRegionsDialog", "<html><head/><body><p>Initializes a new region with the current stage position. Currently, only this button (and Paste Region) can initialize a region.</p></body></html>"))
        self.set_region_button.setText(_translate("AcquisitionRegionsDialog", "Set"))
        self.previous_fish_button.setWhatsThis(_translate("AcquisitionRegionsDialog", "<html><head/><body><p>Sets GUI and current region to Region 1 of the previous fish</p></body></html>"))
        self.previous_fish_button.setText(_translate("AcquisitionRegionsDialog", "Previous Fish"))
        self.previous_region_button.setWhatsThis(_translate("AcquisitionRegionsDialog", "<html><head/><body><p>Sets GUI and current region to the previous region of the current fish</p></body></html>"))
        self.previous_region_button.setText(_translate("AcquisitionRegionsDialog", "Previous Region"))
        self.next_region_button.setWhatsThis(_translate("AcquisitionRegionsDialog", "<html><head/><body><p>Sets GUI and current region to the next region of the current fish. Note that if this button is clicked and there is no next region, you will have to use either the &quot;Set&quot; or &quot;Paste Region&quot; to initialize a region.</p></body></html>"))
        self.next_region_button.setText(_translate("AcquisitionRegionsDialog", "Next Region"))
        self.next_fish_button.setWhatsThis(_translate("AcquisitionRegionsDialog", "<html><head/><body><p>Sets GUI and current region to Region 1 of the next fish. Note that if this button is clicked and there is no region set for the next fish, you will have to use either the &quot;Set&quot; or &quot;Paste Region&quot; to initialize a region.</p></body></html>"))
        self.next_fish_button.setText(_translate("AcquisitionRegionsDialog", "Next Fish"))
        self.remove_region_button.setWhatsThis(_translate("AcquisitionRegionsDialog", "<html><head/><body><p><span style=\" font-weight:400;\">Removes current region and shifts other regions. All regions with higher number in the same fish will be shifted down one. If this is pressed when the current region is the last region of a fish, all regions with a higher fish number will be shifted down one.</span></p></body></html>"))
        self.remove_region_button.setText(_translate("AcquisitionRegionsDialog", "Remove Region"))
        self.snap_exposure_line_edit.setWhatsThis(_translate("AcquisitionRegionsDialog", "<html><head/><body><p>Exposure time of Snap acquisition</p></body></html>"))
        self.snap_exposure_time_label.setText(_translate("AcquisitionRegionsDialog", "Exposure Time:"))
        self.snap_exposure_unit_label.setText(_translate("AcquisitionRegionsDialog", "ms"))
        self.start_z_label.setText(_translate("AcquisitionRegionsDialog", "Start Z:"))
        self.start_z_line_edit.setWhatsThis(_translate("AcquisitionRegionsDialog", "<html><head/><body><p>Start Z position of Z-stack</p></body></html>"))
        self.end_z_label.setText(_translate("AcquisitionRegionsDialog", "End Z:"))
        self.end_z_line_edit.setWhatsThis(_translate("AcquisitionRegionsDialog", "<html><head/><body><p>End Z position of Z-stack</p></body></html>"))
        self.step_size_label.setText(_translate("AcquisitionRegionsDialog", "Stepsize:"))
        self.step_size_line_edit.setWhatsThis(_translate("AcquisitionRegionsDialog", "<html><head/><body><p>Stepsize of Z-stack</p></body></html>"))
        self.start_z_unit_label.setText(_translate("AcquisitionRegionsDialog", "um"))
        self.end_z_unit_label.setText(_translate("AcquisitionRegionsDialog", "um"))
        self.step_size_unit_label.setText(_translate("AcquisitionRegionsDialog", "um"))
        self.x_unit_label.setText(_translate("AcquisitionRegionsDialog", "um"))
        self.y_unit_label.setText(_translate("AcquisitionRegionsDialog", "um"))
        self.z_unit_label.setText(_translate("AcquisitionRegionsDialog", "um"))
        self.video_exposure_line_edit.setWhatsThis(_translate("AcquisitionRegionsDialog", "<html><head/><body><p>Exposure time of Video acquisition. Note that for a continuous video, the exposure time determines the framerate (at a maximum 30 for the PCO camera). If the exposure is 50 ms, for example, the framerate will be 20 fps.</p></body></html>"))
        self.video_exposure_unit_label.setText(_translate("AcquisitionRegionsDialog", "ms"))
        self.video_exposure_time_label.setText(_translate("AcquisitionRegionsDialog", "Exposure Time:"))
        self.video_num_frames_line_edit.setWhatsThis(_translate("AcquisitionRegionsDialog", "<html><head/><body><p>Number of frames per channel to be taken in Video acquisition.</p></body></html>"))
        self.video_num_frames_label.setText(_translate("AcquisitionRegionsDialog", "Number of Frames:"))
        self.region_table_view.setWhatsThis(_translate("AcquisitionRegionsDialog", "<html><head/><body><p>Table that displays the current entries in the Region Settings List in Acquisition Settings. If a Region is not being displayed here, it has not been added to the acquisition. To add a region to the list, you must use the &quot;Set&quot; or &quot;Paste Region&quot; buttons above.</p></body></html>"))
        self.acquisition_setup_button.setWhatsThis(_translate("AcquisitionRegionsDialog", "<html><head/><body><p>Shows the Acquisition Settings Dialog for additional acquisition settings and to start acquisition.</p></body></html>"))
        self.acquisition_setup_button.setText(_translate("AcquisitionRegionsDialog", "Acquisition Setup"))
        self.z_stack_available_list_view.setWhatsThis(_translate("AcquisitionRegionsDialog", "<html><head/><body><p>Current unused and available channels for use in Z-stack</p></body></html>"))
        self.video_used_label.setText(_translate("AcquisitionRegionsDialog", "Used"))
        self.used_z_stack_label.setText(_translate("AcquisitionRegionsDialog", "Used"))
        self.snap_available_label.setText(_translate("AcquisitionRegionsDialog", "Available"))
        self.snap_channel_label.setText(_translate("AcquisitionRegionsDialog", "Channels"))
        self.video_channel_label.setText(_translate("AcquisitionRegionsDialog", "Channels"))
        self.z_stack_used_list_view.setWhatsThis(_translate("AcquisitionRegionsDialog", "<html><head/><body><p>Current channels to be used in Z-stack</p></body></html>"))
        self.snap_used_label.setText(_translate("AcquisitionRegionsDialog", "Used"))
        self.video_used_list_view.setWhatsThis(_translate("AcquisitionRegionsDialog", "<html><head/><body><p>Current channels to be used in Video</p></body></html>"))
        self.available_z_stack_label.setText(_translate("AcquisitionRegionsDialog", "Available"))
        self.snap_used_list_view.setWhatsThis(_translate("AcquisitionRegionsDialog", "<html><head/><body><p>Current channels to be used in Snap</p></body></html>"))
        self.z_stack_channel_label.setText(_translate("AcquisitionRegionsDialog", "Channels"))
        self.snap_available_list_view.setWhatsThis(_translate("AcquisitionRegionsDialog", "<html><head/><body><p>Current unused and available channels for use in Snap</p></body></html>"))
        self.video_available_label.setText(_translate("AcquisitionRegionsDialog", "Available"))
        self.video_available_list_view.setWhatsThis(_translate("AcquisitionRegionsDialog", "<html><head/><body><p>Current unused and available channels for use in Video</p></body></html>"))
        self.copy_region_button.setWhatsThis(_translate("AcquisitionRegionsDialog", "<html><head/><body><p>Creates a copy of the current region to be pasted to a different region</p></body></html>"))
        self.copy_region_button.setText(_translate("AcquisitionRegionsDialog", "Copy Region"))
        self.paste_region_button.setWhatsThis(_translate("AcquisitionRegionsDialog", "<html><head/><body><p>Initializes a region with parameters according to region copied using the Copy Region button. Currently, only this button (and the Set Region Button) can initialize a region.</p></body></html>"))
        self.paste_region_button.setText(_translate("AcquisitionRegionsDialog", "Paste Region"))
        self.set_z_start_button.setWhatsThis(_translate("AcquisitionRegionsDialog", "<html><head/><body><p>Gets current Z-position of stage and sets Z-stack start position to the returned value </p></body></html>"))
        self.set_z_start_button.setText(_translate("AcquisitionRegionsDialog", "Set"))
        self.set_z_end_button.setWhatsThis(_translate("AcquisitionRegionsDialog", "<html><head/><body><p>Gets current Z-position of stage and sets Z-stack end position to the returned value </p></body></html>"))
        self.set_z_end_button.setText(_translate("AcquisitionRegionsDialog", "Set"))
        self.go_to_button.setWhatsThis(_translate("AcquisitionRegionsDialog", "<html><head/><body><p>Moves stage to positions set below</p></body></html>"))
        self.go_to_button.setText(_translate("AcquisitionRegionsDialog", "Go To"))
        self.z_stack_check_box.setWhatsThis(_translate("AcquisitionRegionsDialog", "<html><head/><body><p>Enables Z-stack acquisition for current region based on values entered in Start Z, End Z, and Stepsize. Note that the X and Y positions of the Z-stack are determined by the X and Y values set above.</p></body></html>"))
        self.z_stack_check_box.setText(_translate("AcquisitionRegionsDialog", "Z Stack"))
        self.snap_check_box.setWhatsThis(_translate("AcquisitionRegionsDialog", "<html><head/><body><p>Enables Snap acquisition for current region. A Snap is simply a single image. Note that the position of the Snap is determined by the region position specified above.</p></body></html>"))
        self.snap_check_box.setText(_translate("AcquisitionRegionsDialog", "Snap"))
        self.video_check_box.setWhatsThis(_translate("AcquisitionRegionsDialog", "<html><head/><body><p>Enables Video acquisition for current region based on values entered in Number of Frames and Exposure Time. Note that the position of the Video is determined by the region position specified above.</p></body></html>"))
        self.video_check_box.setText(_translate("AcquisitionRegionsDialog", "Video"))
        self.reset_joystick_button.setWhatsThis(_translate("AcquisitionRegionsDialog", "<html><head/><body><p>Resets the joystick of the stage. If the joystick is ever acting weird, press this. See documentation for more details.</p></body></html>"))
        self.reset_joystick_button.setText(_translate("AcquisitionRegionsDialog", "Reset Joystick"))
        self.add_notes_text_edit.setWhatsThis(_translate("AcquisitionRegionsDialog", "<html><head/><body><p>Additional notes on fish, such as health, additional conditions, etc. Can also be used as notes if your sample isn\'t a fish.</p></body></html>"))
        self.age_label.setText(_translate("AcquisitionRegionsDialog", "Age:"))
        self.inoculum_line_edit.setWhatsThis(_translate("AcquisitionRegionsDialog", "<html><head/><body><p>Inoculum in current fish.</p></body></html>"))
        self.additional_notes_label.setText(_translate("AcquisitionRegionsDialog", "Additional Notes:"))
        self.fish_type_line_edit.setWhatsThis(_translate("AcquisitionRegionsDialog", "<html><head/><body><p>Current fish type, such as genotype, GF, CVZ, etc.</p></body></html>"))
        self.inoculum_label.setText(_translate("AcquisitionRegionsDialog", "Inoculum:"))
        self.fish_type_label.setText(_translate("AcquisitionRegionsDialog", "Fish Type:"))
        self.age_line_edit.setWhatsThis(_translate("AcquisitionRegionsDialog", "<html><head/><body><p>Age of current fish</p></body></html>"))
        self.fish_notes_label.setWhatsThis(_translate("AcquisitionRegionsDialog", "<html><head/><body><p><span style=\" font-size:8pt;\">Notes for current fish. Saved to a separate file called Notes in the acquisition directory when an acquisition is started</span></p></body></html>"))
        self.fish_notes_label.setText(_translate("AcquisitionRegionsDialog", "Fish 1 Notes"))
